//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EMX.rc
//
#define IDS_NEWCOLUMN                   1
#define IDS_NEWMATRIXNAME               2
#define IDS_MATRIXCOPIED                3
#define IDS_NEWCOLUMNNAME               4
#define IDS_COLUMNNAMEBLANK             5
#define IDS_ENTRYERROR                  6
#define IDS_DEFCATEGORY                 7
#define IDS_ADDNEWGRIDTITLE             8
#define IDS_EDITGRIDTITLE               9
#define IDS_DELETEGRIDPROMPT            10
#define IDS_CONFIRMDELETETITLE          11
#define IDS_UNCATEGORIZED               12
#define IDS_GRIDEXISTSHEADING           13
#define IDS_GRIDEXISTSMESSAGE           14
#define IDS_PASSWORDERRHEADING          15
#define IDS_PASSWORDERRMESSAGE          16
#define IDS_ADDGRIDCOLUMNTITLE          17
#define IDS_EDITGRIDCOLUMNTITLE         18
#define IDS_DELETECOLUMNMESSAGE         19
#define IDS_COLHEADNAME                 20
#define IDS_COLHEADTYPE                 21
#define IDS_COLHEADACTIVE               22
#define IDS_COLTYPETEXT                 23
#define IDS_COLTYPEWHOLENUMBER          24
#define IDS_COLTYPEDECIMALNUMBER        25
#define IDS_COLTYPEDATE                 26
#define IDS_YES                         27
#define IDS_NO                          28
#define IDS_RESULTCOLNAME               29
#define IDS_INVALIDMONTH                30
#define IDS_INVALIDDAY                  31
#define IDS_DATAENTRYERRORTITLE         32
#define IDS_INVALIDDATEMESSAGE          33
#define IDS_GRIDEXISTSTITLE             34
#define IDS_INVALIDGRIDNAMETITLE        35
#define IDS_INVALIDGRIDNAMEMESSAGE      36
#define IDS_PASSWORDNOTBLANKMSG         37
#define IDS_SELECTREPOSITORYHEADING     38
#define IDS_CONFIRMDELETEROWS           39
#define IDS_DELETEROWSTOOLTIP           40
#define IDS_INSERTROWTOOLTIP            41
#define IDS_WILDCARDTOOLTIP             42
#define IDS_FULLSCREENTOOLTIP           43
#define IDS_GRIDWIZARDCAPTION           44
#define IDS_NORANGEITEMSDETECTED        45
#define IDS_UNSUPPORTEDACTIVECELLHDG    46
#define IDS_UNSUPPORTEDACTIVECELL       47
#define IDS_UNSUPPORTEDSELECTIONHDG     48
#define IDS_UNSUPPORTEDSELECTION        49
#define IDS_CELLCANNOTBEBLANKHDG        50
#define IDS_CELLCANNOTBEBLANK           51
#define IDS_NOGRIDSUSEDHDG              52
#define IDS_NOGRIDSUSED                 53
#define IDS_FLOATCREATENEWBTN           54
#define IDS_FLOATREFRESHBTN             55
#define IDS_FLOATHIDEBTN                56
#define IDS_FLOATVALUEPAGE_INSERTROWBTN 57
#define IDS_FLOATVALUEPAGE_DELETEROWBTN 58
#define IDS_FLOATVALUEPAGE_WILDCARDBTN  59
#define IDS_FLOATVALUEPAGE_SAVEBTN      60
#define IDS_FLOATVALUEPAGE_CLOSEBTN     61
#define IDS_FLOATVALUEPAGE_REFRESHCHECKBOXBTN 62
#define IDS_FLOATVALUEPAGE_CAPTION      63
#define IDS_FLOATVALUES_SAVEMODIFIEDCAPTION 64
#define IDS_FLOATVALUES_SAVEMODIFIED    65
#define IDS_FLOATVALUEPAGE_RECALCNOWBTN 66
#define IDC_CURSOR1                     134
#define IDC_CURSOR2                     135
#define IDC_CURSOR3                     136
#define IDD_CONFIG_OPTS                 1000
#define IDC_CONFIG_PATHNAME             1000
#define IDC_CONFIG_BROWSEPATH           1001
#define IDD_MATRIX_SELECTOR             1001
#define IDC_MATRIX_TREE                 1002
#define IDB_TREEICONS                   1002
#define IDC_MATRIX_ADD                  1003
#define IDD_MTXEDIT_GENERAL             1003
#define IDC_MATRIX_PROPERTIES           1004
#define IDD_MTXEDIT_COLUMNS             1004
#define IDC_MATRIX_REMOVE               1005
#define IDC_GEN_NAME                    1006
#define IDD_MTXEDIT_DATAVALUES          1006
#define IDC_GEN_CATEGORY                1007
#define IDD_PASSWORD_ENTRY              1007
#define IDC_GEN_REQPSWACCESS            1008
#define IDD_COLEDIT_POSITION            1008
#define IDC_GEN_PSWACCESS               1009
#define IDD_COLEDIT_GENERAL             1009
#define IDC_GEN_REQPSWMODIFY            1010
#define IDC_GEN_PSWACCESS_LBL           1011
#define IDD_COLEDIT_PICKLIST            1011
#define IDC_GEN_PSWMODIFY               1012
#define IDC_GEN_PSWMODIFY_LBL           1013
#define IDB_WILDCARD                    1013
#define IDC_GEN_NOTES                   1014
#define IDB_INSERTROW                   1014
#define IDC_GEN_AUTHOR                  1015
#define IDB_DELETEROW                   1015
#define IDD_COPY_MATRIX_NAME            1015
#define IDC_GEN_FILEPATH                1016
#define IDD_MTXEDIT_DATAVALUESFULL      1016
#define IDB_FULLSCREEN                  1016
#define IDC_COLS_LIST                   1017
#define IDD_WIZ_SELECTMATRIX            1017
#define IDC_COLS_ADD                    1018
#define IDD_WIZ_INSERTPOS               1018
#define IDC_COLS_PROPERTIES             1019
#define IDD_WIZGRID_RANGE               1019
#define IDC_COLS_REMOVE                 1020
#define IDB_GRIDWIZ_SELECTGRID          1020
#define IDC_COLS_RETURNTYPE             1021
#define IDB_GRIDWIZ_RANGES              1021
#define IDD_GRIDWIZ_CHOOSER             1021
#define IDB_GRIDWIZ_INSERTPOS           1022
#define IDD_WIZ_FIELDDEF                1022
#define IDC_PSW_PASSWORD                1023
#define IDB_GRIDWIZ_INSERTGRIDINTOSPREADSHEET 1023
#define IDC_COLEDIT_APPEND              1024
#define IDB_GRIDWIZ_CREATEGRIDFORCOLUMN 1024
#define IDD_WIZ_MATRIXINFO              1024
#define IDC_COLEDIT_INSERT              1025
#define IDB_GRIDWIZ_CREATEGRIDFROMSPREADSHEET 1025
#define IDC_COLEDIT_INSERTLIST          1026
#define IDD_GRWZ_GRIDFROMRANGE          1026
#define IDC_COLEDIT_COLNAME             1027
#define IDB_FGNEW                       1027
#define IDC_COLEDIT_DATATYPE            1028
#define IDB_FGREFRESH                   1028
#define IDR_FLOATCTXT_MENU              1028
#define IDC_COLEDIT_COMPAREOP           1029
#define IDB_FGHIDE                      1029
#define IDC_COLEDIT_COMPARECOL          1030
#define IDC_COLEDIT_NOTES               1031
#define IDB_RECALCNOW                   1031
#define IDC_PICKLIST_USEPICKLIST        1032
#define IDC_PICKLIST_RESTRICT2LIST      1033
#define IDC_PICKLIST_CHOICES_LBL        1034
#define IDC_PICKLIST_CHOICES            1035
#define IDC_GRID_PLACEHOLDER            1036
#define IDC_DATAVALUES_WILDCARD         1037
#define IDC_DATAVALUES_INSERTROW        1038
#define IDC_DATAVALUES_DELETEROW        1039
#define IDC_COLS_MOVEUP                 1040
#define IDC_COLS_MOVEDOWN               1041
#define IDC_MATRIX_COPY                 1042
#define IDC_COPYMATRIX_NAME             1043
#define IDC_DATAVALUES_FULLSCREEN       1044
#define IDC_INSPOS_CELL                 1046
#define IDC_WIZRANGE_LIST               1047
#define IDC_WIZRANGE_REMOVE             1048
#define IDC_GRID_NOTES                  1050
#define IDC_GRIDWIZ_CGCOLUMN            1051
#define IDC_GRIDWIZ_INSGRID             1052
#define IDC_GRIDWIZ_CGIMPORT            1053
#define IDC_GRIDWIZ_INDICATOR           1054
#define IDC_WIZFLD_KEYFIELD             1055
#define IDC_WIZFLD_FIELDTYPE            1056
#define IDC_WIZFLD_OPERATION            1057
#define IDC_WIZFLD_CAPTION              1058
#define IDC_WIZFLD_DATATYPE             1059
#define IDC_WIZFLD_COLINDICATOR         1060
#define IDC_WIZGRIDINFO_RETURNTYPE      1061
#define IDC_WIZGRIDINFO_GRIDNAME        1062
#define IDC_WIZGRIDINFO_DEFVALUE        1063
#define IDC_GWFR_MATRIXNAME             1064
#define IDC_GWFR_FIRSTROWCOLHEADERS     1065
#define IDC_WIZGRIDINFO_LAUNCHEDITOR    1066
#define IDC_CONFIG_RECALCONCHANGE       1067
#define IDC_CONFIG_REFRESHINTERVAL      1068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1032
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
