// This file will be processed by the MIDL tool

/////////////////////////////////////////////////////
//											
// This is a part of the ATL PersistXML add-on
// 
// Copyright (c) VitalyKatasonov.  All rights reserved.
//
// 
//
/////////////////////////////////////////////////////

import "oaidl.idl";
import "ocidl.idl";


	[
		object,
		uuid(B66873EC-BBFF-11D4-A802-112233445566),
		helpstring("IPersistVarXML Interface"),
		pointer_default(unique)
	]
	interface IPersistVarXML : IUnknown
	{
		[propget, helpstring("property ElementName")] HRESULT ElementName([out, retval] BSTR* bstrElementName);
		HRESULT LoadXML([in] VARIANT varSource, [in, optional, defaultvalue(0L)] IUnknown * pAttributes);
		HRESULT SaveXML([in] VARIANT varSource,[in, optional, defaultvalue(1L)] BOOL bSaveContent,[in, optional, defaultvalue("")] BSTR bstrElementName);
	};



